swagger: '2.0'
info:
  version: 1.0.0
  title: Sample 
  description: >
    # Sample RESTFul Web Services

    ---
host: zazvata.com
basePath: /rest
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: >
        # Retrieve the list of users
      parameters:
        - in: query
          name: count
          type: integer
          format: long
          description: number of users to retrieve
          required: true
      responses:
        '200':
          description: Retrieve list of users
        '500':
          description: Internal server error